print('O que uma pulga disse á outra?')
input()
print('Vamos a pé ou esperamos pelo cachorro?')
input()
print()
print('O que um fantasma disse ao outro?')
input()
print('Você acredita em gente?')
input()
print()
print('Você sabe por que a água foi presa?')
input()
print('Porque ela matou a sede.')
input()
print()
print('Por que o professor usava óculos escuros na sala de aula?')
input()
print('Porque os seus alunos eram brilhantes')
input()
print()
print('Qual a diferença entre o penico e a panela?')
input()
print('Se você não sabe, ', end='')
print('nunca me convide para almoçar na sua casa.')
print()
